{{- if .Values.tempo.enable -}}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-deploy.tempo.name" . }}
  labels:
    {{- include "k8s-deploy.tempo.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "k8s-deploy.tempo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.tempo.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "k8s-deploy.tempo.labels" . | nindent 8 }}
        {{- with .Values.tempo.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "k8s-deploy.serviceAccountName" . }}
      {{- with .Values.tempo.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "k8s-deploy.tempo.name" . }}
          {{- with .Values.tempo.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.tempo.image.repository }}:{{ .Values.tempo.image.tag | default .Chart.AppVersion }}"
          args:
            - -config.file=/etc/tempo.yml
          ports:
            - name: grpc
              containerPort: {{ .Values.tempo.service.grpc.containerPort }}
              protocol: TCP
            - name: grafana
              containerPort: {{ .Values.tempo.service.grafanaDatasource.containerPort }}
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/tempo.yml
              name: tempo-conf
              subPath: tempo.yml
      volumes:
        - name: tempo-conf
          configMap:
            name: {{ include "k8s-deploy.tempo.config" . }}


---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-deploy.tempo.grpc.endpoint" . }}
  labels:
    {{- include "k8s-deploy.tempo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.tempo.service.grpc.type }}
  ports:
    - port: {{ .Values.tempo.service.grpc.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "k8s-deploy.tempo.selectorLabels" . | nindent 4 }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-deploy.tempo.grafanaDatasource.endpoint" . }}
  labels:
    {{- include "k8s-deploy.tempo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.tempo.service.grafanaDatasource.type }}
  ports:
    - port: {{ .Values.tempo.service.grafanaDatasource.port }}
      targetPort: grafana
      protocol: TCP
      name: grafana
  selector:
    {{- include "k8s-deploy.tempo.selectorLabels" . | nindent 4 }}
  
---

apiVersion: v1
data:
  tempo.yml: |
    server:
      http_listen_port: {{ .Values.tempo.service.grafanaDatasource.port }}

    distributor:
      receivers: # this configuration will listen on all ports and protocols that tempo is capable of.
        jaeger: # the receives all come from the OpenTelemetry collector.  more configuration information can
          protocols: # be found there: https://github.com/open-telemetry/opentelemetry-collector/tree/main/receiver
            thrift_http:                   #
            grpc:                          # for a production deployment you should only enable the receivers you need!
            thrift_binary:
            thrift_compact:
        zipkin:
        otlp:
          protocols:
            http:
            grpc:
        opencensus:

    ingester:
      max_block_duration: 5m               # cut the headblock when this much time passes. this is being set for demo purposes and should probably be left alone normally

    compactor:
      compaction:
        block_retention: 1h                # overall Tempo trace retention. set for demo purposes

    metrics_generator:
      registry:
        external_labels:
          source: tempo
          cluster: docker-compose
      storage:
        path: /tmp/tempo/generator/wal
        remote_write:
          - url: "http://{{ include "k8s-deploy.prometheus.name" . }}:{{ .Values.prometheus.service.port }}/api/v1/write"
            send_exemplars: true

    storage:
      trace:
        backend: local                     # backend configuration to use
        wal:
          path: /tmp/tempo/wal             # where to store the the wal locally
        local:
          path: /tmp/tempo/blocks

    overrides:
      metrics_generator_processors: [ service-graphs, span-metrics ] # enables metrics generator
kind: ConfigMap
metadata:
  name: {{ include "k8s-deploy.tempo.config" . }}

  {{- end }}