version: '3'

services:
  order-service:
    build: ./
    ports:
      - "4000:8080"
    environment:
      OTEL_TRACES_EXPORTER: "jaeger,zipkin"
      OTEL_EXPORTER_JAEGER_ENDPOINT: "http://jaeger:14250"
      OTEL_EXPORTER_ZIPKIN_ENDPOINT: "http://zipkin:9411/api/v2/spans"
      OTEL_METRICS_EXPORTER: "prometheus"
      OTEL_EXPORTER_PROMETHEUS_PORT: "9464"
      OTEL_EXPORTER_PROMETHEUS_HOST: "0.0.0.0"
      OTEL_LOGS_EXPORTER: "logging"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/opentelemetry"
    depends_on:
      - postgres
      - jaeger-all-in-one
      - zipkin-all-in-one

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: opentelemetry
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "4001:5432"

  jaeger-all-in-one:
    container_name: jaeger
    environment:
      COLLECTOR_OTLP_ENABLED: true
    image: jaegertracing/all-in-one:1.35
    restart: always
    ports:
      - "4002:16686" # HTTP	query	serve frontend
      - "4003:14250" # HTTP	collector	accept model.proto

  zipkin-all-in-one:
    container_name: zipkin
    image: openzipkin/zipkin:3.4
    restart: always
    ports:
      - "4004:9411"

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v3.1.0
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    depends_on:
      - order-service
    ports:
      - "4005:9090"

  grafana:
    container_name: grafana
    image: grafana/grafana
    volumes:
      - ./docker/grafana/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    restart: always
    ports:
      - "4006:3000"
    depends_on:
      - prometheus