spring:
  application:
    name: order-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:4001/opentelemetry
    username: username
    password: password

  sql:
    init:
      mode: always

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true
        default_schema: orders

otel:
  service:
    name: order-service
  resource:
    attributes:
      environment: local
      name: order-service
  exporter:
    otlp:
      endpoint: 'http://localhost:5002'

